# Estágio de Construção para PostgreSQL
FROM postgres:latest-alpine

COPY init-db.sql /docker-entrypoint-initdb.d/
COPY partition-script.sql /docker-entrypoint-initdb.d/
COPY postgresql.conf /etc/postgresql/postgresql.conf
