version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-ponto
    environment:
      POSTGRES_DB: sipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-ponto
    ports:
      - "6379:6379"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
