version: "3.8"
services:
  PostgresDB:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 2416
      POSTGRES_DB: Sistema
    ports:
      - "5433:5432"
    networks:
      - minha-rede
    command: ["postgres", "-c", "max_connections=1000"]

  RedisAG:
    image: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6380:6379"
    networks:
      - minha-rede
servidor-nodejs:
image: servidor-nodejs
build:
context: .
dockerfile: dockerfile
# ports: - "3001:3001"

# volumes: - .\\src:/app/src - .\\views:/app/views

# environment: - NODE_ENV=production
command: ["node", "./dist/server.js"]
