version: "3"

services:
  postgres:
    image: postgres:latest-alpine
    container_name: postgres-ponto
    environment:
      POSTGRES_DB: sipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database159753
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1GB"

  redis:
    image: redis:latest-alpine
    container_name: redis-ponto
    ports:
      - "6379:6379"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
    command: redis-server --save "" --appendonly no --maxclients 20000

  node-app-1:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "1GB"

  node-app-2:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server-api-2
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000" # Use uma porta diferente para cada instância
    env_file:
      - .env
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "1GB"

  nginx:
    image: nginx:latest-alpine
    container_name: nginx-ponto
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin-ponto
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sergipetec.com
      PGADMIN_DEFAULT_PASSWORD: 159753
    depends_on:
      - postgres
    network_mode: "host"

volumes:
  postgres-data:
