version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-test
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ponto-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "0.5GB"

  redis:
    image: redis:alpine
    container_name: redis-test
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ponto-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.25GB"

  node-app-1:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - ponto-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.25GB"

  node-app-2:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server-api-2
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - ponto-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.25GB"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app-1
      - node-app-2
    networks:
      - ponto-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.25GB"

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin-ponto
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sergipetec.com
      PGADMIN_DEFAULT_PASSWORD: 159753
    depends_on:
      - postgres
    networks:
      - ponto-network

networks:
  ponto-network:
    driver: bridge

volumes:
  postgres-data:
