version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-ponto
    environment:
      POSTGRES_DB: sipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database159753
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "2GB"

  redis:
    image: redis:latest
    container_name: redis-ponto
    ports:
      - "6379:6379"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "1GB"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "2GB"

  nginx:
    image: nginx:latest
    container_name: nginx-ponto
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "1GB"

volumes:
  postgres-data:
