version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-ponto-dev
    environment:
      POSTGRES_DB: sipe-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database159753
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ponto-network

  redis:
    image: redis:alpine
    container_name: redis-ponto-dev
    ports:
      - "6379:6379"
    networks:
      - ponto-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server-api-dev
    command: ["echo", "Servidor Node não iniciado"]
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./server:/app/
    networks:
      - ponto-network

  nginx:
    image: nginx:alpine
    container_name: nginx-ponto
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - ponto-network

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin-ponto
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sergipetec.com
      PGADMIN_DEFAULT_PASSWORD: 159753
    depends_on:
      - postgres
    networks:
      - ponto-network

networks:
  ponto-network:
    driver: bridge

volumes:
  postgres-data:
