version: "3"

services:
  postgres:
    image: postgres:16.1-alphine3.19
    container_name: postgres-ponto-dev
    environment:
      POSTGRES_DB: sipe-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database159753
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alphine
    container_name: redis-ponto-dev
    ports:
      - "6379:6379"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server-api-dev
    command: ["echo", "Servidor Node não iniciado"]
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./server:/app/

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx-ponto
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app

volumes:
  postgres-data:
